import Head from 'next/head'
import Image from 'next/image'
import { Inter } from '@next/font/google'
import styles from '@/styles/Home.module.css'
import { GoogleMap, Marker, useLoadScript } from '@react-google-maps/api'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const { isLoaded } = useLoadScript({ googleMapsApiKey: process.env.NEXT_PUBLIC_GOOGLE_MAPS_API_KEY || '' })

  if (!isLoaded) return <p>loading...</p>
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Map />
    </>
  )
}

const position = { lat: 48.9571267, lng: -122.4178804 }

function Map() {
  return (
    <GoogleMap zoom={10} center={position} mapContainerStyle={{ height: '100vh', width: '100%' }}>
      <Marker position={position} />
    </GoogleMap>
  )
}
